import React from 'react';
import { motion } from 'framer-motion';

const PageLayout = ({ title, children }) => (
    <div className="min-h-screen bg-background pt-24 pb-12 px-4">
        <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="container mx-auto max-w-4xl"
        >
            <h1 className="text-4xl font-bold text-white mb-8">{title}</h1>
            <div className="prose prose-invert max-w-none bg-card p-8 rounded-2xl border border-white/10 text-muted-foreground leading-relaxed">
                {children}
            </div>
        </motion.div>
    </div>
);

export const Terms = () => (
    <PageLayout title="Terms & Conditions">
        <p className="mb-6 text-sm">Last Updated: {new Date().toLocaleDateString()}</p>

        <h3 className="text-xl font-semibold text-white mt-6 mb-4">1. Acceptance of Terms</h3>
        <p className="mb-4">
            By accessing and using Dailywin AI ("the Service"), you accept and agree to be bound by the terms and provision of this agreement.
            If you do not agree to abide by these terms, please do not use this Service.
        </p>

        <h3 className="text-xl font-semibold text-white mt-6 mb-4">2. Description of Service</h3>
        <p className="mb-4">
            Dailywin AI provides sports analysis and predictions generated by artificial intelligence.
            These predictions are for informational and entertainment purposes only.
            We do not guarantee the accuracy of any prediction.
        </p>

        <h3 className="text-xl font-semibold text-white mt-6 mb-4">3. Not a Gambling Service</h3>
        <p className="mb-4">
            <strong>Dailywin AI is NOT a gambling, betting, or bookmaking service.</strong>
            We do not accept bets or facilitate gambling in any form.
            Any information provided on this site should not be construed as financial advice or a recommendation to bet.
        </p>

        <h3 className="text-xl font-semibold text-white mt-6 mb-4">4. User Responsibilities</h3>
        <ul className="list-disc pl-6 mb-4 space-y-2">
            <li>You must be at least 18 years of age (or the legal age of majority in your jurisdiction) to use this Service.</li>
            <li>You are responsible for ensuring that your use of the Service complies with all local laws and regulations regarding online content and sports betting in your jurisdiction.</li>
            <li>You agree not to share your account credentials with others.</li>
            <li>You agree not to scrape, copy, or redistribute our data without permission.</li>
        </ul>

        <h3 className="text-xl font-semibold text-white mt-6 mb-4">5. Disclaimer of Warranties</h3>
        <p className="mb-4">
            The Service is provided on an "as is" and "as available" basis.
            We make no warranties regarding the accuracy, reliability, or completeness of the data or predictions provided.
            Past performance of the AI is not indicative of future results.
        </p>

        <h3 className="text-xl font-semibold text-white mt-6 mb-4">6. Limitation of Liability</h3>
        <p className="mb-4">
            To the fullest extent permitted by law, Dailywin AI shall not be liable for any direct, indirect, incidental, special, consequential, or exemplary damages,
            including but not limited to, damages for loss of profits, goodwill, use, data, or other intangible losses resulting from the use or the inability to use the Service.
            You assume full responsibility for any betting decisions you make.
        </p>

        <h3 className="text-xl font-semibold text-white mt-6 mb-4">7. Termination</h3>
        <p className="mb-4">
            We reserve the right to terminate or suspend your account and access to the Service immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach the Terms.
        </p>
    </PageLayout>
);

export const Privacy = () => (
    <PageLayout title="Privacy Policy">
        <p className="mb-6 text-sm">Last Updated: {new Date().toLocaleDateString()}</p>

        <h3 className="text-xl font-semibold text-white mt-6 mb-4">1. Information We Collect</h3>
        <p className="mb-4">
            We collect minimal information to provide our services properly and improve your experience.
        </p>
        <ul className="list-disc pl-6 mb-4 space-y-2">
            <li><strong>Account Information:</strong> Email address and encrypted password when you register.</li>
            <li><strong>Usage Data:</strong> We monitor how you interact with our site (e.g., pages visited, clicks) to improve our AI models and user experience.</li>
            <li><strong>Technical Data:</strong> IP address, browser type, and device information for security and analytics.</li>
        </ul>

        <h3 className="text-xl font-semibold text-white mt-6 mb-4">2. How We Use Your Information</h3>
        <p className="mb-4">
            We use your information to:
        </p>
        <ul className="list-disc pl-6 mb-4 space-y-2">
            <li>Authenticate your access to the Service.</li>
            <li>Send important account updates (e.g., password resets, service announcements).</li>
            <li>Analyze aggregate usage trends to improve our AI predictions.</li>
            <li>Detect and prevent fraud or abuse of our services.</li>
        </ul>

        <h3 className="text-xl font-semibold text-white mt-6 mb-4">3. Data Protection</h3>
        <p className="mb-4">
            We implement industry-standard security measures (encryption, secure servers) to protect your personal information.
            We do not sell, trade, or rent your personal identification information to others.
        </p>

        <h3 className="text-xl font-semibold text-white mt-6 mb-4">4. Cookies and Tracking Technologies</h3>
        <p className="mb-4">
            We use cookies to maintain your login session and remember your preferences.
            We may also use third-party analytics tools (like Google Analytics) that use cookies to collect anonymous usage data.
            You can choose to disable cookies in your browser, but some features of the site (like logging in) may not function properly.
        </p>

        <h3 className="text-xl font-semibold text-white mt-6 mb-4">5. GDPR (General Data Protection Regulation) Rights</h3>
        <p className="mb-4">
            If you are a resident of the European Economic Area (EEA), you have certain data protection rights, including:
        </p>
        <ul className="list-disc pl-6 mb-4 space-y-2">
            <li>The right to access, update or to delete the information we have on you.</li>
            <li>The right of rectification.</li>
            <li>The right to object.</li>
            <li>The right of restriction.</li>
        </ul>
        <p className="mb-4">To exercise these rights, please contact us at admin@dailywin.space.</p>

        <h3 className="text-xl font-semibold text-white mt-6 mb-4">6. CCPA (California Consumer Privacy Act) Rights</h3>
        <p className="mb-4">
            If you are a California resident, you have the right to request what personal data we collect, use, disclosure, and sell.
            Dailywin AI does not sell your personal data.
        </p>
    </PageLayout>
);

export const Contact = () => (
    <PageLayout title="Contact Us">
        <div className="space-y-6">
            <p className="text-lg">
                We value your feedback and are here to help with any questions regarding our AI predictions or your account.
            </p>

            <div className="p-6 bg-white/5 rounded-xl border border-white/10">
                <h3 className="text-xl font-semibold mb-4 text-white">Get in Touch</h3>
                <div className="flex flex-col gap-4">
                    <div className="flex items-center gap-3">
                        <div className="w-10 h-10 rounded-full bg-primary/20 flex items-center justify-center text-primary">📧</div>
                        <div>
                            <p className="text-sm text-muted-foreground">General Support</p>
                            <a href="mailto:admin@dailywin.space" className="text-white hover:text-primary transition-colors font-medium">admin@dailywin.space</a>
                        </div>
                    </div>
                </div>
            </div>

            <div className="p-6 bg-white/5 rounded-xl border border-white/10">
                <h3 className="text-xl font-semibold mb-4 text-white">Support Hours</h3>
                <p className="mb-2">Our team is available:</p>
                <p className="text-white font-medium">Monday - Friday: 9:00 AM - 6:00 PM (UTC)</p>
                <p className="text-sm text-muted-foreground mt-2">We aim to respond to all inquiries within 24 hours.</p>
            </div>

            <div className="p-6 bg-white/5 rounded-xl border border-white/10">
                <h3 className="text-xl font-semibold mb-4 text-white">Business Inquiries</h3>
                <p className="text-sm text-muted-foreground">
                    For partnerships, API access, or media inquiries, please reach out to the same email address with the subject line "Partnership".
                </p>
            </div>
        </div>
    </PageLayout>
);
